name: Lint

on:
  push:
    paths:
      - '.github/workflows/lint.yaml'
      - '.hlint.yaml'
      - 'Agda.cabal'
      - 'src/**'
      - 'test/**'

  pull_request:
    # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/lint.yaml'
      - '.hlint.yaml'
      - 'Agda.cabal'
      - 'src/**'
      - 'test/**'

jobs:
  hlint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.1

    - name: Set up hlint
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: Run hlint
      uses: rwe/actions-hlint-run@v1
      with:
        path: '["src/", "test/"]'
        fail-on: warning
